export const TOGGLE_MODAL = 'TOGGLE_MODAL'

export const TOGGLE_AUTH ='TOGGLE_AUTH'
export const TOGGLE_FETCH_LOADER = 'TOGGLE_FETCH_LOADER'
export const TOGGLE_PAGE_LOADER = 'TOGGLE_PAGE_LOADER'
export const WRITE_AUTH_MESSAGE = 'WRITE_AUTH_MESSAGE'
export const WRITE_USERNAME = 'WRITE_USERNAME'


export const WRITE_CATEGORIES = 'WRITE_CATEGORIES'
export const WRITE_SUBCATEGORIES = 'WRITE_SUBCATEGORIES'
export const WRITE_CATEGORY_BY_ID = 'WRITE_CATEGORY_BY_ID'
export const ADDED_CATEGORY = 'ADDED_CATEGORY'
export const DELETED_CATEGORY = 'DELETED_CATEGORY'
export const UPDATED_CATEGORY = 'UPDATED_CATEGORY'


export const WRITE_QAS = 'WRITE_QAS'
export const WRITE_QAS_BY_ID = 'WRITE_QAS_BY_ID'
export const ADDED_QAS = 'ADDED_QAS'
export const DELETED_QAS = 'DELETED_QAS'
export const UPDATED_QAS = 'UPDATED_QAS'

export const WRITE_RULE = 'WRITE_RULE'
export const WRITE_RULE_BY_ID = 'WRITE_RULE_BY_ID'
export const ADDED_RULE = 'ADDED_RULE'
export const DELETED_RULE = 'DELETED_RULE'
export const UPDATED_RULE = 'UPDATED_RULE'

export const WRITE_ABOUT = 'WRITE_ABOUT'
export const WRITE_ABOUT_BY_ID = 'WRITE_ABOUT_BY_ID'
export const ADDED_ABOUT = 'ADDED_ABOUT'
export const DELETED_ABOUT = 'DELETED_ABOUT'
export const UPDATED_ABOUT = 'UPDATED_ABOUT'


export const WRITE_INSTRUCTION = 'WRITE_INSTRUCTION'
export const WRITE_INSTRUCTION_BY_ID = 'WRITE_INSTRUCTION_BY_ID'
export const ADDED_INSTRUCTION = 'ADDED_INSTRUCTION'
export const DELETED_INSTRUCTION = 'DELETED_INSTRUCTION'
export const UPDATED_INSTRUCTION = 'UPDATED_INSTRUCTION'

export const WRITE_SPECIALISTS = 'WRITE_CATEGORIES'
export const WRITE_SPECIALIST_BY_ID = 'WRITE_CATEGORY_BY_ID'
export const ADDED_SPECIALIST = 'ADDED_CATEGORY'
export const DELETED_SPECIALIST = 'DELETED_CATEGORY'
export const UPDATED_SPECIALIST = 'UPDATED_CATEGORY'


export const WRITE_RECORD_ID = 'WRITE_RECORD_ID'
export const WRITE_ELEMENTS_TO_DELETE = 'WRITE_ELEMENTS_TO_DELETE'
export const WRITE_TABLE_MESSAGE = 'WRITE_TABLE_MESSAGE'


export const WRITE_STATISTIC = 'WRITE_STATISTIC'
export const WRITE_LAST_ACTIONS = 'WRITE_LAST_ACTIONS'
export const WRITE_CITIES = 'WRITE_CITIES'
export const WRITE_USERS = 'WRITE_USERS'
export const WRITE_USER_BY_ID = 'WRITE_USER_BY_ID'
export const ADDED_USER = 'ADDED_USER'
export const DELETED_USER = 'DELETED_USER'
export const UPDATED_USER = 'UPDATED_USER'


export const USER_TOGGLE_FETCH_LOADER = 'USER_TOGGLE_FETCH_LOADER'
export const SPECIALIST_TOGGLE_FETCH_LOADER = 'SPECIALIST_TOGGLE_FETCH_LOADER'
export const INSTRUCTION_TOGGLE_FETCH_LOADER = 'INSTRUCTION_TOGGLE_FETCH_LOADER'
export const ABOUT_TOGGLE_FETCH_LOADER = 'ABOUT_TOGGLE_FETCH_LOADER'
export const RULE_TOGGLE_FETCH_LOADER = 'RULE_TOGGLE_FETCH_LOADER'
export const QAS_TOGGLE_FETCH_LOADER = 'QAS_TOGGLE_FETCH_LOADER'
export const CATEGORY_TOGGLE_FETCH_LOADER = 'CATEGORY_TOGGLE_FETCH_LOADER'
export const AUTH_TOGGLE_FETCH_LOADER = 'AUTH_TOGGLE_FETCH_LOADER'
export const MAIN_TOGGLE_FETCH_LOADER = 'MAIN_TOGGLE_FETCH_LOADER'

