export const TOGGLE_MODAL = 'TOGGLE_MODAL'

export const TOGGLE_AUTH ='TOGGLE_AUTH'
export const TOGGLE_FETCH_LOADER = 'TOGGLE_FETCH_LOADER'
export const TOGGLE_PAGE_LOADER = 'TOGGLE_PAGE_LOADER'
export const WRITE_AUTH_MESSAGE = 'WRITE_AUTH_MESSAGE'
export const WRITE_USERNAME = 'WRITE_USERNAME'


export const WRITE_CATEGORIES = 'WRITE_CATEGORIES'
export const WRITE_SUBCATEGORIES = 'WRITE_SUBCATEGORIES'
export const WRITE_CATEGORY_BY_ID = 'WRITE_CATEGORY_BY_ID'
export const ADDED_CATEGORY = 'ADDED_CATEGORY'
export const DELETED_CATEGORY = 'DELETED_CATEGORY'
export const UPDATED_CATEGORY = 'UPDATED_CATEGORY'


export const WRITE_SPECIALISTS = 'WRITE_CATEGORIES'
export const WRITE_SPECIALIST_BY_ID = 'WRITE_CATEGORY_BY_ID'
export const ADDED_SPECIALIST = 'ADDED_CATEGORY'
export const DELETED_SPECIALIST = 'DELETED_CATEGORY'
export const UPDATED_SPECIALIST = 'UPDATED_CATEGORY'


export const WRITE_RECORD_ID = 'WRITE_RECORD_ID'
export const WRITE_ELEMENTS_TO_DELETE = 'WRITE_ELEMENTS_TO_DELETE'
export const WRITE_TABLE_MESSAGE = 'WRITE_TABLE_MESSAGE'


export const WRITE_STATISTIC = 'WRITE_STATISTIC'
export const WRITE_LAST_ACTIONS = 'WRITE_LAST_ACTIONS'
export const WRITE_CITIES = 'WRITE_CITIES'


export const WRITE_USERS = 'WRITE_USERS'
export const WRITE_USER_BY_ID = 'WRITE_USER_BY_ID'

export const DELETED_USER = 'DELETED_USER'
export const UPDATED_USER = 'UPDATED_USER'

